services:
  nyt-midi-receipt:
    build: .
    container_name: nyt-midi-receipt
    restart: unless-stopped
    ports:
      - "6434:6434"
    environment:
      PRINTER_HOST: 192.168.10.11
      RECEIPT_WIDTH: 48
